#! /bin/sh

# Starting sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Basic settings
bspc monitor -d I II III IV V

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

# Border
bspc config border_width 2
bspc config window_gap 10

bspc config focused_border_color        "#5e81ac"
bspc config normal_border_color         "#2e3440"
bspc config active_border_color         "#2e3440"

# Space on top for polybar
bspc config top_padding 30

#
# Autostart
#

# Bar
sh ~/.config/polybar/launch.sh &

# Notifications
/home/piotr/.config/dunst/launch.sh &

# Wallpaper
feh --bg-fill --randomize /walls/*.* &

# Picom
picom --experimental-backend &

# Network Applet
nm-applet --indicator &

# Bluetooth Applet
blueberry-tray &
